# Generated by Django 4.2.3 on 2023-08-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='choose',
        ),
    ]
